services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: shipment-app
        container_name: shipment-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "90:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: rehlaty
            POSTGRES_USER: rehlaty
            POSTGRES_PASSWORD: secret
        ports:
            - "5433:5432"
        volumes:
            - pGData:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - app-network

volumes:
    pGData:

networks:
    app-network:
        driver: bridge
